//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos
    {
        public bancos()
        {
            this.trabajador_copy = new HashSet<trabajador_copy>();
            this.trabajador = new HashSet<trabajador>();
        }
    
        public int Idbanco { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<trabajador_copy> trabajador_copy { get; set; }
        public virtual ICollection<trabajador> trabajador { get; set; }
    }
}
