//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class campotra
    {
        public int idcampotra { get; set; }
        public int idtrabajador { get; set; }
        public string nombrecampo { get; set; }
        public decimal valor { get; set; }
    }
}
