//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class campos
    {
        public int idcampo { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> valorinicial { get; set; }
        public Nullable<int> esReiniciado { get; set; }
        public string descripcion { get; set; }
    }
}
