//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public cargo()
        {
            this.trabajador = new HashSet<trabajador>();
        }
    
        public int idcargo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string conceptos { get; set; }
        public Nullable<int> Iddepartamentos { get; set; }
        public string sidcargo { get; set; }
    
        public virtual departamentos departamentos { get; set; }
        public virtual ICollection<trabajador> trabajador { get; set; }
    }
}
