//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptos
    {
        public conceptos()
        {
            this.prenominagen = new HashSet<prenominagen>();
            this.prenomina = new HashSet<prenomina>();
        }
    
        public int idconcepto { get; set; }
        public string nombre { get; set; }
        public string variante { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipo { get; set; }
        public string Valor { get; set; }
        public string codigo { get; set; }
        public int noimprimir { get; set; }
        public int desactivar { get; set; }
    
        public virtual ICollection<prenominagen> prenominagen { get; set; }
        public virtual ICollection<prenomina> prenomina { get; set; }
    }
}
