//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlconfig
    {
        public Nullable<decimal> MinHorasDia { get; set; }
        public Nullable<decimal> MaxHorasDia { get; set; }
        public Nullable<System.DateTime> IniJorDiurna { get; set; }
        public Nullable<System.DateTime> IniJorNocTurna { get; set; }
        public int idcontrol { get; set; }
        public string WHorasD { get; set; }
        public string WDia { get; set; }
        public string WHorasN { get; set; }
        public string WHorasEx { get; set; }
        public string WDiaF { get; set; }
        public string WInasistencia { get; set; }
        public Nullable<int> MaxEntradas { get; set; }
        public Nullable<int> MaxTimeCheck { get; set; }
        public Nullable<decimal> MinRetrasos { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
    }
}
