//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlconfig
    {
        public Nullable<decimal> MinHorasDia { get; set; }
        public Nullable<decimal> MaxHorasDia { get; set; }
        public Nullable<System.DateTime> IniJorDiurna { get; set; }
        public Nullable<System.DateTime> IniJorNocTurna { get; set; }
        public int idcontrol { get; set; }
        public string WHorasD { get; set; }
        public string WDia { get; set; }
        public string WHorasN { get; set; }
        public string WHorasEx { get; set; }
        public string WDiaF { get; set; }
        public string WInasistencia { get; set; }
        public Nullable<int> MaxEntradas { get; set; }
        public Nullable<int> MaxTimeCheck { get; set; }
        public Nullable<int> MinRetrasos { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
    }
}
