//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int Idempresa { get; set; }
        public string RazonSocial { get; set; }
        public string Rif { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string TipodeLicencia { get; set; }
        public string NumerodeLicencia { get; set; }
        public string Email { get; set; }
        public string Contacto { get; set; }
        public string Logo { get; set; }
        public string Detallelogo { get; set; }
    }
}
