//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class jornada
    {
        public int idjornada { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Lunes { get; set; }
        public Nullable<int> Martes { get; set; }
        public Nullable<int> Miercoles { get; set; }
        public Nullable<int> Jueves { get; set; }
        public Nullable<int> Viernes { get; set; }
        public Nullable<int> Sabado { get; set; }
        public Nullable<int> Domingo { get; set; }
        public string Horariodesde { get; set; }
        public string Horariohasta { get; set; }
        public string Descansodesde { get; set; }
        public string Descansohasta { get; set; }
        public Nullable<int> descanso { get; set; }
    }
}
