//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class jornada
    {
        public int idjornada { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Lunes { get; set; }
        public Nullable<int> Martes { get; set; }
        public Nullable<int> Miercoles { get; set; }
        public Nullable<int> Jueves { get; set; }
        public Nullable<int> Viernes { get; set; }
        public Nullable<int> Sabado { get; set; }
        public Nullable<int> Domingo { get; set; }
        public string Horariodesde { get; set; }
        public string Horariohasta { get; set; }
        public string Descansodesde { get; set; }
        public string Descansohasta { get; set; }
        public Nullable<int> descanso { get; set; }
    }
}
