//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominatype
    {
        public nominatype()
        {
            this.prenominagen = new HashSet<prenominagen>();
            this.prenomina = new HashSet<prenomina>();
            this.nominauni = new HashSet<nominauni>();
            this.trabajador = new HashSet<trabajador>();
            this.trabajador1 = new HashSet<trabajador>();
        }
    
        public int idnomina { get; set; }
        public string descripcion { get; set; }
        public int intervalo { get; set; }
        public string conceptos { get; set; }
        public string scodigo { get; set; }
        public int tipo { get; set; }
    
        public virtual ICollection<prenominagen> prenominagen { get; set; }
        public virtual ICollection<prenomina> prenomina { get; set; }
        public virtual ICollection<nominauni> nominauni { get; set; }
        public virtual ICollection<trabajador> trabajador { get; set; }
        public virtual ICollection<trabajador> trabajador1 { get; set; }
    }
}
