//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominatype
    {
        public nominatype()
        {
            this.nominauni = new HashSet<nominauni>();
            this.prenominagen = new HashSet<prenominagen>();
            this.prenomina = new HashSet<prenomina>();
            this.trabajador_copy = new HashSet<trabajador_copy>();
            this.trabajador = new HashSet<trabajador>();
            this.trabajador1 = new HashSet<trabajador>();
        }
    
        public int idnomina { get; set; }
        public string descripcion { get; set; }
        public int intervalo { get; set; }
        public string conceptos { get; set; }
        public string scodigo { get; set; }
        public int tipo { get; set; }
    
        public virtual ICollection<nominauni> nominauni { get; set; }
        public virtual ICollection<prenominagen> prenominagen { get; set; }
        public virtual ICollection<prenomina> prenomina { get; set; }
        public virtual ICollection<trabajador_copy> trabajador_copy { get; set; }
        public virtual ICollection<trabajador> trabajador { get; set; }
        public virtual ICollection<trabajador> trabajador1 { get; set; }
    }
}
