//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominatype
    {
        public nominatype()
        {
            this.trabajador = new HashSet<trabajador>();
        }
    
        public int idnomina { get; set; }
        public string descripcion { get; set; }
        public int intervalo { get; set; }
        public string conceptos { get; set; }
    
        public virtual ICollection<trabajador> trabajador { get; set; }
    }
}
