//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominauni
    {
        public int idnominauni { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public Nullable<decimal> totalnomina { get; set; }
        public Nullable<decimal> totalasignaciones { get; set; }
        public Nullable<decimal> totaldeducciones { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<int> cantidadt { get; set; }
        public int idnomina { get; set; }
    
        public virtual nominatype nominatype { get; set; }
    }
}
