//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominauni
    {
        public int idnomina { get; set; }
        public Nullable<int> nominatype { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public Nullable<decimal> totalnomina { get; set; }
        public Nullable<decimal> totalasignaciones { get; set; }
        public Nullable<decimal> totaldeducciones { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<int> cantidadt { get; set; }
    }
}
