//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nominaEntities : DbContext
    {
        public nominaEntities()
            : base("name=nominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bancos> bancos { get; set; }
        public DbSet<campos> campos { get; set; }
        public DbSet<campotra> campotra { get; set; }
        public DbSet<cargo> cargo { get; set; }
        public DbSet<departamentos> departamentos { get; set; }
        public DbSet<estatus> estatus { get; set; }
        public DbSet<gradointruc> gradointruc { get; set; }
        public DbSet<jornada> jornada { get; set; }
        public DbSet<prenomina> prenomina { get; set; }
        public DbSet<prenominagen> prenominagen { get; set; }
        public DbSet<procedures> procedures { get; set; }
        public DbSet<tipocuenta> tipocuenta { get; set; }
        public DbSet<usermenu> usermenu { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<usertype> usertype { get; set; }
        public DbSet<variables> variables { get; set; }
        public DbSet<varsys> varsys { get; set; }
        public DbSet<conceptos> conceptos { get; set; }
        public DbSet<nacionalidad> nacionalidad { get; set; }
        public DbSet<nominaini> nominaini { get; set; }
        public DbSet<nominatype> nominatype { get; set; }
        public DbSet<trabajador> trabajador { get; set; }
        public DbSet<nominauni> nominauni { get; set; }
    }
}
