//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class prenomina
    {
        public int idprenomina { get; set; }
        public int idnominatype { get; set; }
        public Nullable<int> idtrabajador { get; set; }
        public Nullable<int> idconcepto { get; set; }
        public string nombrecon { get; set; }
        public Nullable<decimal> valorconcepto { get; set; }
        public Nullable<decimal> valorvar { get; set; }
        public Nullable<int> tipoconcepto { get; set; }
        public Nullable<int> idnominagen { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
    
        public virtual conceptos conceptos { get; set; }
        public virtual nominatype nominatype { get; set; }
        public virtual trabajador trabajador { get; set; }
    }
}
