//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador
    {
        public int idtrabajador { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public string telefonocel { get; set; }
        public string telefonolocal { get; set; }
        public string telefonocontacto { get; set; }
        public string nombrecontacto { get; set; }
        public string correo { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public string conceptos { get; set; }
        public Nullable<int> sexo { get; set; }
        public Nullable<System.DateTime> Fechaing { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public Nullable<int> edocivil { get; set; }
        public Nullable<int> Nhijos { get; set; }
        public string lugarnac { get; set; }
        public string dirfoto { get; set; }
        public string numerocuenta { get; set; }
        public string tipocuenta { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual estatus estatus { get; set; }
        public virtual gradointruc gradointruc { get; set; }
        public virtual nacionalidad nacionalidad { get; set; }
        public virtual nominatype nominatype { get; set; }
    }
}
