//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermenu
    {
        public string id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Pariente { get; set; }
        public string Accion { get; set; }
        public Nullable<int> Seleccionado { get; set; }
        public Nullable<int> hijos { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> Guardar { get; set; }
        public Nullable<int> Editar { get; set; }
        public Nullable<int> Eliminar { get; set; }
        public int Idmenu { get; set; }
    }
}
