//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermenu
    {
        public string id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Pariente { get; set; }
        public string Accion { get; set; }
        public string Parametros { get; set; }
        public Nullable<int> Seleccionado { get; set; }
        public Nullable<int> hijos { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> Guardar { get; set; }
        public Nullable<int> Editar { get; set; }
        public Nullable<int> Eliminar { get; set; }
        public int Idmenu { get; set; }
    }
}
