//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class varsys
    {
        public Nullable<int> idtrabajador { get; set; }
        public string cedula { get; set; }
        public Nullable<int> vDIASDES { get; set; }
        public Nullable<decimal> vDLAB { get; set; }
        public Nullable<decimal> vVHIJOS { get; set; }
        public Nullable<decimal> vDF { get; set; }
    }
}
